# The URL the site will be built for
base_url = "https://wellness-sanctuary.pages.dev"

title = "Wellness Sanctuary Dental Clinic"
description = "Wellness Sanctuary Dental Clinic"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

# The default language; used in feeds.
default_language = "en"

[extra]
# User settings
username = "Wellness Sanctuary"
user_description = "I will remember that there is art to dental medicine as well as science, and that warmth, sympathy, and understanding may outweigh the surgeon's knife or the chemist's drug. I will prevent disease whenever I can, for prevention is preferable to cure. I will remember that I remain a member of society, with special obligations to all my fellow human beings, those sound of mind and body as well as the infirm. If I do not violate this oath, may I enjoy life and art, respected while I live and remembered with affection thereafter. May I always act so as to preserve the finest traditions of my calling and may I long experience the joy of healing those who seek my help."
user_title = "By Dr. Milarosa Chua-Samson"
email = "milarosasamson@gmail.com"
twitter_username = "lorem_ipsum"
github_username =  "lorem_ipsum"
gplus_username =  "lorem_ipsum"

# Google-analytics
google_analytics.id = ""
